[package]
name = "av_exclusion"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Arteii <ben.arteii@proton.me>"]
build = "build.rs"

# TODO!:
categories = ["command-line-interface"]
repository = "https://github.com/Arteiii/av_exclusion"
keywords = ["windows", "av"]
homepage = "https://arteiii.github.io"


include = [
    "Cargo.toml",
    "LICENSE-MIT",
    "src/**/*",
]

[lib]
name = "av_exclusion_lib"
path = "src/lib.rs"

[[bin]]
name = "av_exclusion"
path = "src/main.rs"

[dependencies]
winapi = { version = "0.3.9", features = ["winbase", "processthreadsapi", "securitybaseapi", "winnt", "errhandlingapi"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
OriginalFilename = "av_exclusion.exe"
LegalCopyright = "Copyright Arteii © 2024"
